force-app/main/default/objects/DHA_Class_Assignment__c/DHA_Class_Assignment__c.object-meta.xml
<CustomObject>
    <label>DHA Class Assignment</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>DHA Class  Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Class Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/DHA_Study_Result__c.object-meta.xml
<CustomObject>
    <label>DHA Study Result</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>DHA Study Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Study Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/fields/DHA_Class_Assignment__c.field-meta.xml
<CustomField>
    <fullName>DHA_Class_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DHA Class Assignment</label>
    <referenceTo>DHA_Class_Assignment__c</referenceTo>
    <relationshipLabel>DHA Study Results</relationshipLabel>
    <relationshipName>DHA_Study_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/fields/Final_Score__c.field-meta.xml
<CustomField>
    <fullName>Final_Score__c</fullName>
    <formula>(IF(ISNULL(Score_1__c),0,Score_1__c) + IF(ISNULL(Score_2__c),0,Score_2__c) + IF(ISNULL(Score_3__c),0,Score_3__c)) / 3</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/fields/Is_Latest__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Not Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DHA_StudyResultHelper.cls
public without sharing class DHA_StudyResultHelper {
    public static Boolean skipMarkAsLatest = false;

    
    public void beforeUpdate(Map<Id,SObject> newMap, Map<Id,SObject> oldMap) 
    {   
        if(skipMarkAsLatest == true)
        {
            return;
        }
        
        if(skipMarkAsLatest == false)
        {
            Integer passScore = DHA_Helper.getOrgDefaults_DHA_ManagementSetting('DHA_Study_Result__c');
            List<Object> parameters = new List<Object>{passScore};
            String errorMessage = String.format('Cannot update this result because Final Score is less than {0}', parameters);
            
            for(Id studyId :newMap.keySet())
            {   
                DHA_Study_Result__c newStudyResult = (DHA_Study_Result__c) newMap.get(studyId);
                if(newStudyResult.Is_Latest__c == false)
                {
                    // 1. update Is_Latest__c of new records to true when it is updated
                    newStudyResult.Is_Latest__c = true;
                    
                }

                DHA_Study_Result__c oldStudyResult = (DHA_Study_Result__c) oldMap.get(studyId);
                // oldStudyResult != null
                if(oldStudyResult.Result__c != newStudyResult.Result__c && newStudyResult.Result__c == 'Passed')
                {
                    if(newStudyResult.Final_Score__c < passScore)
                    {
                        newStudyResult.Result__c.addError(errorMessage);
                    }
                }
            
            }
    }
    
    }        

    public void afterUpdate(List<DHA_Study_Result__c> lstStudyResult)
    {   
        if(skipMarkAsLatest == true)
        {
            return;
        }
        Set<Id> idStudyResultSet = new Set<Id>();
        Set<String> classAssignmentSet = new Set<String>();
        //  build sets needed to query
        for(DHA_Study_Result__c studyResult :lstStudyResult)
        {
            idStudyResultSet.add(studyResult.Id);
            classAssignmentSet.add(studyResult.DHA_Class_Assignment__c);
        }

        //  query record which associates with class assignment (not oursefl)
        List<DHA_Study_Result__c> studyResultQuery = [SELECT Is_Latest__c FROM DHA_Study_Result__c 
                                                WHERE Is_Latest__c = true 
                                                AND  DHA_Class_Assignment__c IN :classAssignmentSet
                                                    AND Id NOT IN :idStudyResultSet ];

        // 2. set Is_Latest__c to false
        for(DHA_Study_Result__c studyResult_toUpdate :studyResultQuery)
        {
            studyResult_toUpdate.Is_Latest__c = false;
        }
        // 3. update record
        
        skipMarkAsLatest = true;
        update studyResultQuery;

 
    }
    

    // update Is_Latest__c of all new records to true when new results are created
    public void beforeInsert(List<DHA_Study_Result__c> lstStudyResult)
    {
        for(DHA_Study_Result__c studyResult :lstStudyResult)
        {
            studyResult.Is_Latest__c = true;
        }
    }
    // the older results in the same class assignment should have Is_Latest__c equals to false
    public void afterInsert(List<DHA_Study_Result__c> lstStudyResult)
    {
        List<DHA_Study_Result__c> olderResults = new List<DHA_Study_Result__c>();
        Set<String> classAssignmentSet = new Set<String>();
        Set<ID> studyIdSet = new Set<ID>();

        //1. build sets to query
        for(DHA_Study_Result__c studyResult :lstStudyResult )
        {
            classAssignmentSet.add(studyResult.DHA_Class_Assignment__c); 
            studyIdSet.add(studyResult.Id); // Id ourseft
        }

        // 2. query for all other DHA_Study_Result__c (not to query ourself) with matching classAssignmentSet
        for(DHA_Study_Result__c studyResult :[ SELECT Is_Latest__c FROM DHA_Study_Result__c 
                                                WHERE Is_Latest__c = true
                                                AND DHA_Class_Assignment__c IN :classAssignmentSet
                                                AND Id NOT IN :studyIdSet])
        {
            studyResult.Is_Latest__c = false;
            olderResults.add(studyResult);
        }
        //3. update older DHA_Study_Result__c
        try {
            skipMarkAsLatest = true;
            update olderResults;
            System.debug('Updated older study result ');
        } catch (Exception ex) {
            System.debug('Exception in afterInsert : ' + ex);
        }
    }

}