force-app/main/default/objects/DHA_Class__c/DHA_Class__c.object-meta.xml
<CustomObject>
    <label>DHA Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>DHA Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Class_Assignment__c/DHA_Class_Assignment__c.object-meta.xml
<CustomObject>
    <label>DHA Class Assignment</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>DHA Class  Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Class Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Class_Assignment__c/fields/DHA_Student__c.field-meta.xml
<CustomField>
    <fullName>DHA_Student__c</fullName>
    <label>DHA Student</label>
    <referenceTo>DHA_Student__c</referenceTo>
    <relationshipLabel>DHA Classs</relationshipLabel>
    <relationshipName>DHA_Classs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHA_Management_Setting__c/fields/Max_Assigned_Classes__c.field-meta.xml
<CustomField>
    <fullName>Max_Assigned_Classes__c</fullName>
    <defaultValue>15</defaultValue>
    <label>Max Assigned Classes</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHA_Management_Setting__c/fields/Max_Students_In_Class__c.field-meta.xml
<CustomField>
    <fullName>Max_Students_In_Class__c</fullName>
    <defaultValue>120</defaultValue>
    <label>Max Students In Class</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHA_Management_Setting__c/fields/Pass_Score__c.field-meta.xml
<CustomField>
    <fullName>Pass_Score__c</fullName>
    <label>Pass Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHA_Student__c/DHA_Student__c.object-meta.xml
<CustomObject>
    <label>DHA Student</label>
    <nameField>
        <label>DHA Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DHA Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/DHA_Study_Result__c.object-meta.xml
<CustomObject>
    <label>DHA Study Result</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>DHA Study Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Study Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/fields/DHA_Class_Assignment__c.field-meta.xml
<CustomField>
    <fullName>DHA_Class_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DHA Class Assignment</label>
    <referenceTo>DHA_Class_Assignment__c</referenceTo>
    <relationshipLabel>DHA Study Results</relationshipLabel>
    <relationshipName>DHA_Study_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DHA_Helper.cls
public with sharing class DHA_Helper {
    public DHA_Helper() {

    }
    public static Integer getOrgDefaults_DHA_ManagementSetting(String sObjectName)
    {
        try {
            DHA_Management_Setting__c dha_Management_Setting =  DHA_Management_Setting__c.getvalues(Userinfo.getUserId());

            if(dha_Management_Setting == null){
                dha_Management_Setting = DHA_Management_Setting__c.getvalues(Userinfo.getProfileId());
            }

            if(dha_Management_Setting == null){
                dha_Management_Setting = DHA_Management_Setting__c.getOrgDefaults();
            }

            if(sObjectName == 'DHA_Class__c')
            {
                return dha_Management_Setting.Max_Assigned_Classes__c.intValue();
            }
            else if(sObjectName == 'DHA_Student__c') {
                return dha_Management_Setting.Max_Students_In_Class__c.intValue();
            }
            else if(sObjectName == 'DHA_Study_Result__c') {
                return dha_Management_Setting.Pass_Score__c.intValue();
            }
        }
        catch (Exception ex) 
        {
            System.debug('Return -1, Error in method getMaxAssignedClasses(), message: ' + ex); 
        }
        return 0;
    }

    public static Integer getOrgDefaults(String fieldName)
    {
        try {
            DHA_Management_Setting__c dha_Management_Setting =  DHA_Management_Setting__c.getvalues(Userinfo.getUserId());

            if(dha_Management_Setting == null){
                dha_Management_Setting = DHA_Management_Setting__c.getvalues(Userinfo.getProfileId());
            }

            if(dha_Management_Setting == null){
                dha_Management_Setting = DHA_Management_Setting__c.getOrgDefaults();
            }

            if(fieldName == 'Max_Assigned_Classes__c')
            {
                return dha_Management_Setting.Max_Assigned_Classes__c.intValue();
            }
            else if(fieldName == 'Max_Students_In_Class__c') {
                return dha_Management_Setting.Max_Students_In_Class__c.intValue();
            }
            else if(fieldName == 'Pass_Score__c') {
                return dha_Management_Setting.Pass_Score__c.intValue();
            }
        }
        catch (Exception ex) 
        {
            System.debug('Return -1, Error in method getMaxAssignedClasses(), message: ' + ex); 
        }
        return 0;
    }

    public static Boolean isActiveTrigger(String field)
    {
        try {
            DHA_Management_Setting__c DHA_triggerSetting =  DHA_Management_Setting__c.getvalues(Userinfo.getUserId());

            if(DHA_triggerSetting == null){
                DHA_triggerSetting = DHA_Management_Setting__c.getvalues(Userinfo.getProfileId());
            }

            if(DHA_triggerSetting == null){
                DHA_triggerSetting = DHA_Management_Setting__c.getOrgDefaults();
            }

            if(DHA_triggerSetting == null)
            {
                return true;
            }
            else {
                return Boolean.valueOf(DHA_triggerSetting.get(field));
            }
            
        } catch (Exception ex) {
            return true; 
        }
    }




    //
    /* [Select DHA_Class__c, count(Id)numberClass from DHA_Class_Assignment__c Group By DHA_Class__c]    
        [
            {DHA_Class__c: 'a0C5i000005nYsUEAU', cound(id): 2},
            {DHA_Class__c: 'a0C5i000005ncgyEAA', cound(id): 1}
        ]

        getSumClass('a0C5i000005nYsUEAU') -> 2  */

    public static Integer getSumClass(String className)
    {
        Integer returnValue = -1;
        List<AggregateResult> total_class = [Select DHA_Class__c, count(Id)sumClass from DHA_Class_Assignment__c Group By DHA_Class__c];
        for(AggregateResult result :total_class)
            {
                if(result.get('DHA_Class__c') == className)
                {
                    returnValue = (Integer) result.get('sumClass');
                    return returnValue;
                }
            }
        return returnValue;
    }
    


        //
    /* [Select DHA_Student__c, count(Id)sumStudent from DHA_Class_Assignment__c Group By DHA_Student__c]    
        [
            {DHA_Student__c: 'a0A5i000002WfxkEAC', cound(id): 2},
            {DHA_Student__c: 'a0A5i000002WeizEAC', cound(id): 1},
            {DHA_Student__c: 'a0A5i000002WdxjEAC', cound(id): 1}
        ]

    getNumberClass('a0C5i000005nYsUEAU') -> 2  */
    public static Integer getSumStudent(String studentName)
    {
        Integer returnValue = -1;
        List<AggregateResult> total_student = [Select DHA_Student__c, count(Id)sumStudent from DHA_Class_Assignment__c Group By DHA_Student__c];
        for(AggregateResult result :total_student)
            {
                if(result.get('DHA_Student__c') == studentName)
                {
                    returnValue = (Integer) result.get('sumStudent');
                    return returnValue;
                }
            }
        return returnValue;
    }


}