force-app/main/default/objects/DHA_Class__c/DHA_Class__c.object-meta.xml
<CustomObject>
    <label>DHA Class</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>DHA Class Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Classes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Class_Assignment__c/DHA_Class_Assignment__c.object-meta.xml
<CustomObject>
    <label>DHA Class Assignment</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>DHA Class  Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Class Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Class_Assignment__c/fields/DHA_Student__c.field-meta.xml
<CustomField>
    <fullName>DHA_Student__c</fullName>
    <label>DHA Student</label>
    <referenceTo>DHA_Student__c</referenceTo>
    <relationshipLabel>DHA Classs</relationshipLabel>
    <relationshipName>DHA_Classs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DHA_Student__c/DHA_Student__c.object-meta.xml
<CustomObject>
    <label>DHA Student</label>
    <nameField>
        <label>DHA Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DHA Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/DHA_Study_Result__c.object-meta.xml
<CustomObject>
    <label>DHA Study Result</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>DHA Study Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Study Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/fields/DHA_Class_Assignment__c.field-meta.xml
<CustomField>
    <fullName>DHA_Class_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DHA Class Assignment</label>
    <referenceTo>DHA_Class_Assignment__c</referenceTo>
    <relationshipLabel>DHA Study Results</relationshipLabel>
    <relationshipName>DHA_Study_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/fields/Is_Latest__c.field-meta.xml
<CustomField>
    <fullName>Is_Latest__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Latest</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/DHA_ClassAssignmentHelper.cls
public class DHA_ClassAssignmentHelper {
    
    public void beforeInsert(List<DHA_Class_Assignment__c> lstDHA_Class_Assignment)
    {
        // Rule: Student’s assigned classes should not be greater than DHA_Management_Setting__c.Max_Assigned_Class__c
        Integer max_Assigned_Classes = DHA_Helper.getOrgDefaults_DHA_ManagementSetting('DHA_Class__c');
        
        for(DHA_Class_Assignment__c assignment :lstDHA_Class_Assignment)
        {
            Integer sumClass = DHA_Helper.getSumClass(assignment.DHA_Class__c);
            if(sumClass < max_Assigned_Classes)
            {
                System.debug('Added assignment!');
            }
            else {
                assignment.DHA_Class__c.addError('There is no seat to join this class.');
            }
        }
        // Rule: Student’s assigned classes should not be greater than DHA_Management_Setting__c.Max_Assigned_Class__c
        //Integer max_Student_In_Class = DHA_Helper.getOrgDefaults_DHA_ManagementSetting('DHA_Student__c');
        for(DHA_Class_Assignment__c assignment :lstDHA_Class_Assignment )
        {
            Integer sumStudent = DHA_Helper.getSumStudent(assignment.DHA_Student__c);
            if(sumStudent < max_Assigned_Classes)
            {
                System.debug('Added assignment!');
            }
            else {
                assignment.DHA_Class__c.addError('This student is attending to too much class.');
            }
        }
    }

    public void afterInsert(List<DHA_Class_Assignment__c> lstDHA_Class_Assignment)
    {
        List<DHA_Study_Result__c> newStudyResults = new  List<DHA_Study_Result__c>();

        for(DHA_Class_Assignment__c item :lstDHA_Class_Assignment)
        {
            newStudyResults.add(new DHA_Study_Result__c(DHA_Class_Assignment__c = item.Id, Is_Latest__c= true));
        }
        if(!newStudyResults.isEmpty())
        {
            insert newStudyResults;
        }
    }

   
}