force-app/main/default/objects/DHA_Study_Result__c/DHA_Study_Result__c.object-meta.xml
<CustomObject>
    <label>DHA Study Result</label>
    <nameField>
        <displayFormat>ST-{0000}</displayFormat>
        <label>DHA Study Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DHA Study Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DHA_Study_Result__c/fields/Final_Score__c.field-meta.xml
<CustomField>
    <fullName>Final_Score__c</fullName>
    <formula>(IF(ISNULL(Score_1__c),0,Score_1__c) + IF(ISNULL(Score_2__c),0,Score_2__c) + IF(ISNULL(Score_3__c),0,Score_3__c)) / 3</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Final Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DHA_Study_Result__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passed</fullName>
            </value>
            <value>
                <fullName>Not Passed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/studyResultUpdateBatch.cls
public  class studyResultUpdateBatch implements Database.batchable<sObject>, Database.Stateful {

    private Integer passedScore;
    private Integer successUpdate;
    public studyResultUpdateBatch()
    {
        this.passedScore = DHA_Helper.getOrgDefaults('Pass_Score__c');
        this.successUpdate = 0;
    }
    // Update Result__c to Passed if Final_Score__c > DHA_Mangement_Setting__c.Passed_Score__c

    public Database.QueryLocator start(Database.BatchableContext bc){ 
        String query = 'SELECT Result__c FROM DHA_Study_Result__c WHERE Final_Score__c > ' + passedScore;
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<SObject> scope){
        for(SObject studyResult :scope)
        {
            studyResult.put('Result__c','Passed' );
            successUpdate++;
        }
        update scope;
    }

    public void finish(Database.BatchableContext info){
        System.debug('===== execute batch successfully ======');
        System.debug(successUpdate + ' Result updated');  
    }

}